rm imports_*
rm exports_*
rm completed-*
rm node_a/imports_*
rm node_a/exports_*
rm node_a/completed-*
rm node_a/seen_*
rm node_b/imports_*
rm node_b/exports_*
rm node_b/seen_*
rm node_b/location_a/data/*